[versions]
agp = "8.9.1"
kotlin = "2.2.0"
coreKtx = "1.16.0"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2025.04.00"
kotlinxSerialization = "1.9.0"
iasdk = "0.0.19-3"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

# IA SDK
iasdk-integrations = { group = "de.ihreapotheken.sdk", name = "integrations", version.ref = "iasdk" }
iasdk-otc = { group = "de.ihreapotheken.sdk", name = "otc", version.ref = "iasdk" }
iasdk-ordering = { group = "de.ihreapotheken.sdk", name = "ordering", version.ref = "iasdk" }
iasdk-pharmacy = { group = "de.ihreapotheken.sdk", name = "pharmacy", version.ref = "iasdk" }
iasdk-rx = { group = "de.ihreapotheken.sdk", name = "rx", version.ref = "iasdk" }

[bundles]
# IA SDK bundle
iasdk = [
    "iasdk-integrations",
    "iasdk-otc",
    "iasdk-ordering",
    "iasdk-pharmacy",
    "iasdk-rx"
]

# IA SDK bundle
iasdk-example3 = [
    "iasdk-integrations",
    "iasdk-ordering",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
